export default {
    "office.hybrid_working": { sheet: "sprite-02.webp", index: 3 },
    "office.external_monitor": { sheet: "sprite-02.webp", index: 1 },
    "financial.project_bonus": { sheet: "sprite-01.webp", index: 0 },
    "financial.macbook_installment": { sheet: "sprite-01.webp", index: 2 },
    "office.modern_office": { sheet: "sprite-03.webp", index: 1 },
    "office.company_macbook": { sheet: "sprite-02.webp", index: 2 },
    "financial.lunch_voucher": { sheet: "sprite-01.webp", index: 3 },
    "learning.mentoring": { sheet: "sprite-08.webp", index: 2 },
    "culture.employee_award": { sheet: "sprite-10.webp", index: 3 },
    "culture.innovation_reward": { sheet: "sprite-11.webp", index: 0 },
    "culture.founder_session": { sheet: "sprite-12.webp", index: 0 },
    "culture.peer_appreciation": { sheet: "sprite-12.webp", index: 1 },
    "financial.transport_allowance": { sheet: "sprite-02.webp", index: 0 },
    "health.sports": { sheet: "sprite-09.webp", index: 2 },
    "office.private_workspace": { sheet: "sprite-05.webp", index: 1 },
    "side.freelance_project": { sheet: "sprite-08.webp", index: 3 },
    "learning.ai_subscription": { sheet: "sprite-07.webp", index: 1 },
    "learning.weekly_training": { sheet: "sprite-06.webp", index: 3 },
    "learning.course_budget": { sheet: "sprite-07.webp", index: 0 },
    "office.free_snack": { sheet: "sprite-04.webp", index: 1 }
};